### ISSUE TITLE
Add this apisix-authz middleware to the official list

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/apisix-authz#5]
See docs: https://apisix.apache.org/docs/apisix/plugins/wolf-rbac

Source code for the docs: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/wolf-rbac.md

We may name it to "casbin-authz"

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
@hsluoyz Sure, I will first add the core API functions like add/remove/update/has/get - policy and grouping policy to this plugin. And then we will also need to update the [Casbin](https://luarocks.org/modules/hsluoyz/casbin) module on LuaRocks with the latest rockspec (v1.16.1) so that we can include it as a dependency for other LuaRocks modules.

**Comment by hsluoyz** [comment]
@rushitote is there a way to setup an auto-release to LuaRocks (like semantic-release)?

**Comment by rushitote** [comment]
@hsluoyz I will try to setup one.

**Comment by rushitote** [comment]
Opened an initial issue at [#4674](https://github.com/apache/apisix/issues/4674).

**Comment by hsluoyz** [comment]
@rushitote kudos! Great work for making Casbin into Apisix! From what I see in: https://github.com/apache/apisix/pull/4710/files , the source code of this repo is already merged into apisix's code base. So do we still need this repo here?

**Comment by rushitote** [comment]
@hsluoyz Thanks, and yes this repo is no longer required.

**Comment by hsluoyz** [comment]
Done by: https://github.com/apache/apisix/pull/4710
